apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: ubi8
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: registry.redhat.io/ubi8/ubi-minimal:8.2
      name: "8.2"
